# Generated by Django 4.1.3 on 2022-12-04 11:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('follower', models.CharField(default='admin', max_length=40)),
                ('following', models.CharField(default='admin', max_length=40)),
            ],
        ),
    ]
