# Generated by Django 4.1.3 on 2022-12-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_event',
            field=models.CharField(default='all', max_length=40),
        ),
    ]
